/*-----------------------------------------------------------------------------
    Name: Checkout_preview_CMD
    Generated By: cavisson
    Date of generation: 10/27/2022 05:34:18
    Flow details:
    Build details: 4.8.0 (build# 122)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"
#include "util.c"

void Checkout_preview_CMD()
{
	

	     int loop_count  = 0;
		initialize_job_id();
		
    ns_start_transaction("Put_Checkout_Previews_V3_CMD_MEMBER");
    ns_web_url ("Put_Checkout_Previews_V3_CMD_MEMBER",
        "URL=https://{endpoint}/buy/checkout_previews/v3/{job-id}",
       // "URL=https://auth.test.commerce.nikecloud.com.cn/buy/checkout_previews/v3/{job-id}",
        "METHOD=PUT",
        "HEADER=x-nike-visitorid:d8816bbf-4e63-4765-b159-c553e41629f1",
        "HEADER=Accept:application/json",
        "HEADER=appid:com.nike.commerce.nikedotcom.web",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=x-nike-visitid:1",
        "HEADER=X-Forwarded-For:192.168.0.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
        "HEADER=True-Client-IP:192.168.0.1",
        "HEADER=Content-Type:application/json",
        "HEADER=cloud_stack:buy_auto_perf",
        "HEADER=Authorization: Bearer {token}",

        
       BODY_BEGIN,
            "{
    "request": {
        "email": "{userEmail}",
        "country": "CN",
        "currency": "CNY",
        "locale": "zh_CN",
        "channel": "NIKECOM",
        "clientInfo": {
            "deviceId": "0400nyhffR+vPCUNf94lis1ztol5d9dCHB246/Ao2WE9gwpcE7v8aPDcWj/epLbL94In8c6z42TBuWd9l5a0IyQqrWpPeeaRgFdrdUsprl5Sq8nl3OCiMt8Ua7Ft29Nm9E0wo3tqUrLsBHilRNM4vbTYwHClB11+ifZBex1TLARybUqvwFRqyepQW4stPHxOZiJVdLDs+1JC1RHeqz7TtH33U/i4F83yZ4OkFmQWppRl6Bv4pp48B2PR0LUM6Rn3JtHEfF9hXdZ4DRRiwxmZVjl9I9Crygmlz2/FpSOst6q0+dS7rzbxH0ZCbqQct2fIUhDBCu2Vndk9hzrCB+h6dwpvkw/EdgYhG5CG5E5vA66uHN7j/qESFaJvp0Xpq0/C5bvShrGwb1cKcUBCHbxLfjGyRJ2fs6nXFKkWrCq2SH5g9qu7HLiS6doU16C1fbK9PQn1dOIYgHC/3QY1fZwSVtWNySwAqo7XEZwLIcXbgOJHT6jqMH5mYxq87tK3Sga2t5uGiUmVth62ac8r2IJ/IFV5csTFqRHCrxoAx7yacWI+PSJlRRf504RRRh0RkdwdXCZU6vXVtqw/LjmixPMqjFULp9I8UWAJoym9T+HoQVdeZcQEvJcwI6Behq1o7SCXf5dYxKmKi0E5mbKKRrn6YOiFer1/Y9e8eiB47caT1pbMLWoRqB9DI9E5KbD9av+SeN9VqKVNlMbJNAZc8V1ZIWK++ykzCGBlggcGImwI4pTgqhaL5GG+2liAsUxFXRiZcQcAnPGnG3CqgLln+4KLswTyWhDAstLN4US5V97h50/5jKuarMe13sn+Ml70rcgY4Iqwy8ep10NX3Gug5dRbGWPI8BWlyqreR+Y/s6BJDQXN+VxrVbGJnVrTPdWGCE8s0cL/Ut+AS8NGHzVYBOIn7xyv6fehTqT3rw1rUL/Q9DBUr0B8X2Fd1ngNFGSttdZygKPcQVL2duy/r6Bk2cfD0IHAIf2vFnup4QVZw6tHOqYnoKuXKbiqJ593K0ZpMoS1bffn4hvooZW2uAoW4N8bOSDWHqMDfWcaXS+M624L7HjSv/bUT6BBP395oyw+Jld00Kp8rjH2w8LkbqRTKc7uW80aEwalR6tq92sLof950W4kmx4Hyf83JPkBAvdbw86vRscVZ/lrwsKFYh1C4MHuHozkPSBfcDhwAT1javSu9sFFV3ncE4nZ3meVnqg0ESQ1nWNXktIpFe3sKDLYXo3BTCX2hln1Bau9lgps6/Ao2WE9gwpcE7v8aPDcWhU5jvm54Ebr5sdrzcINkHrCB+h6dwpvkw/EdgYhG5CG5E5vA66uHN7j/qESFaJvp0Xpq0/C5bvShrGwb1cKcUB7oZ1+3UXTApVPfVKB9sZJi9y9EyZXAnkwZvNcAmq0GW8ZoO3JHcGFezo++G0WXGj3x8s4WlPsRhMXZZmDRGeoIi7SoUevORoRB7c5x/6fl5wVWm/jtVkJWPtDm2OONsvvIXUucsdOnbLr4Qc8kEwoYtoFcXZDcQU="
        },
        "items":[{"id":"{skuId}","skuId":"{skuId}","productId":"{productId}","itemCosts":{"priceInfo":{"price":{price},"subtotal":{price},"discount":0,"valueAddedServices":0,"taxTotal":0,"total":{price}}},"quantity":1,"fulfillmentDetails":{"type":"SHIP","getBy":{ItemgetBySP},"location":{"id":"23252d75-47da-4272-a2c0-027bf7f02a20","postalAddress":{"address1":"江湾城路99号尚浦中心1号楼李娜楼一楼&","city":"上海市","state":"CN-31","county":"静安区","country":"CN","postalCode":"200438","preferred":false,"email":"{userEmail}","phoneNumber":"{userPhone}","addressId":"1a67c0b7-8fcc-44fe-be93-01c595242cbe"},"type":"address/shipping"}},"recipient":{"firstName":"Foo","lastName":"Bar"},"contactInfo":{"phoneNumber":"{userPhone}","email":"{userEmail}"}}],
        "promotionCodes": []
    }
}",
        BODY_END
    );
    ns_end_transaction("Put_Checkout_Previews_V3_CMD_MEMBER", NS_AUTO_STATUS);
    set_think_time_for_cmd_qry("Put_Checkout_Previews_V3_CMD_MEMBER", "CMD", &loop_count);

   ns_page_think_time(0.2);

qry_start:
    ns_start_transaction("Get_Checkout_Previews_V3_QRY_MEMBER");
    ns_web_url ("Get_Checkout_Previews_V3_QRY_MEMBER",
       "URL=https://{endpoint}/buy/checkout_previews_jobs/v3/{job-id}",
       // "URL=https://auth.test.commerce.nikecloud.com.cn/buy/checkout_previews_jobs/v3/{job-id}",
        "METHOD=GET",
        "HEADER=x-nike-visitorid:d8816bbf-4e63-4765-b159-c553e41629f1",
        "HEADER=Accept:application/json",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=x-nike-visitid:1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
        "HEADER=cloud_stack:buy_auto_perf",
        "HEADER=Authorization: Bearer {token}",

	  );


    if(atoi(ns_eval_string("{CP_Qry_5xx_count}")) > 0 )
    {
  	   log_txn_time("Get_Checkout_Previews_V3_QRY_MEMBER", ns_eval_string("{traceid}"));
  	   ns_end_transaction_as("Get_Checkout_Previews_V3_QRY_MEMBER", NS_AUTO_STATUS,"Get_Checkout_Previews_V3_QRY_MEMBER_5xx");
    }
    else 
    {
       ns_end_transaction("Get_Checkout_Previews_V3_QRY_MEMBER", NS_AUTO_STATUS);
    }



    
        int ret = set_think_time_for_cmd_qry("Get_Checkout_Previews_V3_QRY_MEMBER", "QRY", &loop_count);    
        if(ret == 0) // Not completed yet (in case of completed or error, break)
        goto qry_start;

   

   // ns_page_think_time(0.5);
}