/*-----------------------------------------------------------------------------
    Name: Checkout_Preview_QRY
    Generated By: cavisson
    Date of generation: 10/27/2022 05:40:55
    Flow details:
    Build details: 4.8.0 (build# 122)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void Checkout_Preview_QRY()
{

// ns_start_transaction("Get_Checkout_Previews_V3_QRY_MEMBER");
//    ns_web_url ("Get_Checkout_Previews_V3_QRY_MEMBER",
//       // "URL=https://{endpoint}/buy/checkout_previews_jobs/v3/{job-id}",
//        "URL=https://auth.test.commerce.nikecloud.com.cn/buy/checkout_previews_jobs/v3/{job-id}",
//        "METHOD=GET",
//        "HEADER=x-nike-visitorid:d8816bbf-4e63-4765-b159-c553e41629f1",
//        "HEADER=Accept:application/json",
//        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
//        "HEADER=x-nike-visitid:1",
//        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
//        "HEADER=cloud_stack:buy_auto_perf",
//        "HEADER=Authorization: Bearer {token}",
//        
//
//        
//    );
//    ns_end_transaction("Get_Checkout_Previews_V3_QRY_MEMBER", NS_AUTO_STATUS);
//
//
//    ns_page_think_time(0.5);

}