/*-----------------------------------------------------------------------------
    Name: Fulfilment_offerings
    Generated By: cavisson
    Date of generation: 10/27/2022 05:26:42
    Flow details:
    Build details: 4.8.0 (build# 122)
    Modification History:
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"


void Fulfilment_offerings()
{

    ns_start_transaction("Fulfillment_offerings_v1_MEMBER");
    ns_web_url ("Fulfillment_offerings_v1_MEMBER",
        "URL=https://{endpoint}/buy/fulfillment_offerings/v1?filter=countryCode(CN)&filter=currency(CNY)&filter=skuId({skuId})&filter=offeringTypes(SHIP)&filter=userType(nike:plus)",
       // "URL=https://public.test.commerce.nikecloud.com.cn/buy/fulfillment_offerings/v1?filter=countryCode(CN)&filter=currency(CNY)&filter=skuId({skuId})&filter=offeringTypes(SHIP)&filter=userType(nike:plus)",
        "METHOD=GET",
        "HEADER=Accept:text/plain,application/json,text/html,application/javascript,application/xml",
        "HEADER=User-Agent:Mozilla/5.0 (Windows; U; Windows NT 6.0; de-DE) AppleWebKit/533.21.1 (KHTML, like Gecko) Version/5.0.5 Safari/533.21.1",
        "HEADER=Accept-Encoding: gzip, deflate, br, compress;q=0.9",
        "HEADER=cloud_stack:buy_auto_perf",
	   "HEADER=Authorization: Bearer {token}",
    );
    ns_end_transaction("Fulfillment_offerings_v1_MEMBER", NS_AUTO_STATUS);

    ns_page_think_time(0.1);

}