/*-----------------------------------------------------------------------------
    Name: Token
    Generated By: Brajesh
    Date of generation: 06/23/2022 02:51:22
    Flow details:
    Build details: 4.8.0 (build# 144)
    Modification History:
-----------------------------------------------------------------------------*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>
//#include <openssl/sha.h>
#include "ns_string.h"
//#include "util_token.c"

/*
    Purpose:
    This flow file will generate token once every 50 minutes in each CVM. This token will be used by all Vusers on one CVM.
	So if there are 100 generators and each generator is using 5 CVM, then it will generate 100*4 = 400 tokens.
	If token generation is in progres, then other vuser will not generate but keep using from a saved buffer
	
	Notes:
    When new user is used, paramaters are not available to next session as it is new user. 
    So we need to store token in a static buffer and refresh it
	
	Parameters:
    Add a parameter using json parameter to extract from token API
        dyn_token_jp
	Script will use following parameter	
		token
	token can be file parameter if using file parameter else declare parameter	
*/

#define MAX_TOKEN_SIZE 1024

static long last_token_gen_time = 0;            // Last token refresh time in ms
static char dyn_token_buf[MAX_TOKEN_SIZE + 1];  // Buffer for keeping the token
static int  last_token_gen_start_time = 0;      // token generation start ts. Used to control only one token generation is done at a time

#define TOKEN_EXPIRY_DURATION (60*60*1000)      // 1 hour is ms
#define TOKEN_EXPIRY_BUFFER   (10*60*1000)      // 10 min in ms
//#define TOKEN_EXPIRY_BUFFER (59*60*1000)
// ns_save_string(const char param_value, const char param_name);
// char ns_get_param_val(char variable_name, char buf, int len);

void Token()
{ 	
	long cur_ts = ns_get_ms_stamp(); //This is the relative time stamp from the start of the test.
	
#ifdef NS_DEBUG_ON
    fprintf(stdout, "Token(): Method called. last_token_gen_time = %ld, cur_ts = %ld, dyn_token_buf = %s\n", last_token_gen_time, cur_ts, dyn_token_buf);
#endif

	if((last_token_gen_time != 0) && ((cur_ts - last_token_gen_time) < (TOKEN_EXPIRY_DURATION - TOKEN_EXPIRY_BUFFER)))
    {
	    ns_save_string(dyn_token_buf, "token");
#ifdef NS_DEBUG_ON
        fprintf(stdout, "Token(): Token not expired. Copied saved token from buffer to token parameter. last_token_gen_start_time = %d, dyn_token_buf = %s, token = %s\n", last_token_gen_start_time, dyn_token_buf, ns_eval_string("{token}"));
#endif
        return;
	}	

    // Instead of keeping token generation in progress flag, we are keeping start ts. 
	// This is done to avoid situations where API may fail and continue on page error is not set. So in progress flag will never to reset to 0
	if((last_token_gen_start_time != 0) && ((cur_ts - last_token_gen_start_time) < 120000))  // Less than 2 minutes
    {
    	   while(dyn_token_buf[0] == '\0') // if token is not generated we need to wait. (this will happen only for 1st session of a user.)
    	         ns_page_think_time(1);
	   ns_save_string(dyn_token_buf, "token");  
#ifdef NS_DEBUG_ON
        fprintf(stdout, "Token(): Token generation already in progress. Copied saved token from buffer to token parameter. last_token_gen_start_time = %d, dyn_token_buf = %s, token = %s\n", last_token_gen_start_time, dyn_token_buf, ns_eval_string("{token}"));
#endif
        return;
	}	

    last_token_gen_start_time = cur_ts;
//#ifdef NS_DEBUG_ON
    fprintf(stdout, "Token(): Generating token\n");
//#endif	

//    fill_code_verifier_param("codeVerifier");
//    fill_code_challenge_param("codeChallenger", ns_eval_string("{codeVerifier}"));

 	ns_auth0_gen_code_verifier("codeVerifier");
   	ns_auth0_gen_code_challenge("codeChallenger", ns_eval_string("{codeVerifier}"));

         // get code from request 
    ns_start_transaction("TokenCheckV1");
	ns_web_url ("v1_7",
		"URL=https://accounts-test.nike.com.cn/check/v1",
		"METHOD=POST",
		"HEADER=sec-ch-ua:\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\"",
		"HEADER=sec-ch-ua-mobile:?0",
		"HEADER=content-type:application/json",
		"HEADER=Origin:https://accounts-test.nike.com.cn",
		"HEADER=Sec-Fetch-Site:same-origin",
		"HEADER=Sec-Fetch-Mode:same-origin",
		"HEADER=Sec-Fetch-Dest:empty",
		"HEADER=Accept-Language:en-US,en;q=0.9",                     	
		"HEADER=Referer: https://accounts-test.nike.com.cn/challenge?client_id=e586fabad2bfc03bf416f6a5419837a4&redirect_uri=https://demo.l7r-test.nikecloud.com.cn/&response_type=code&scope=openid%20nike.digital%20profile%20email%20phone%20flow&state={state}&code_challenge={codeChallenger}&code_challenge_method=S256",
		"HEADER=Cookie:acw_tc=dde5cb7016558197441408985e5b6478e3a2ecfe822ce459c2b118aae1; emperor_id=ff55935a-ba82-47ea-ba64-3a8e59ed90b8; anonymousId=4Cl1i9TSnrgLf5AA; _uab_collina=165581974918155886277354; ssxmod_itna=QqAO0IOGkG7DOYDXY=OMDfoq0ExROh7ODDIPE50dD/8RmD3q0=GFDf473E8pRnbNRW+u4Fq5Coq4FCti0cRqjCWfg5FVb4B3DE=k0q3bDeeDvDCeDIDWeDiDG4GmIxGU7D7qDdUEs5NCDYPDEB9=DGeDegK8DY5DhxDCDGFHDQKDugF+1c7QFFyDo9iqUxG1740HOm8oUPEfjF4so33EZW4DUAkqpniUGCioqR48DlI2DCKz2nyQFIkC/pyGEDaebluqCm1FEi4xOmGx+arKNG0xdiRPOyzoDDaXFlr3NYD=; ssxmod_itna2=QqAO0IOGkG7DOYDXY=OMDfoq0ExROh7ODDIPE5iG9Fs7DBTMx7p+xSIpQa7CGFYmMqjKn/aL2Ds52hhgXQnzlDF6GqdzQOK6Yur0SrhSGaSA2KhNw=+BXNXbIYMmd=/uo5XtEXpKrBpnxz2pO==c8Apqhv1Fq12F8=UA85/wrNinH7buxsliHV0x=NK9N57uWdhSWgWPFt18=BiPQ6x96nRB6ESeh7zIWizdenifp73af=j5IsClfy3p1PHSWlAMcNhcwDwuwdAZO5YzzgmcHvZGucCFP5/AuK1I5H8mo2vwgnXVz=jUSPKIoPPDqEGQ2pfWcwPiq5bj1Ze5bK4x6hcP3tpbDqbcvtffv7QKzvW=Q2OQRGblpwVgLjiICCvmmwUD6nnGq+t+xoHrQApe2xrzgmEWp/x+M1Q4iohpDPPpjGvN35zoPQrIZYeQ=oACT4xmXSPDRLLiFzzeIhRwQQ3hPpCohnwS0d9lL4oTl9wEUXB9Hxay36v5Oqpj4DQFKtioUqgQI8Yp+OCrQRxzQxYPAG25SywWTK4qOyix5i=BDAuOqQRKe+4b45tSOFGpExxfD=Ri/WZqE66=45/vjxU=zGqd5x4mrF00d6qViKD08DiQtF4iW4QTO57KicpIcA5W+VZxSQMaRx0dz35wbe/VhhC81MESju7qjz2czrfmY1Zc5E0dqeD=; acw_sc__v2=62b1ce04e0d1ab97042d6aec5ec7703baf5964f7; ua_state=0c79c50e3dabd1e44b0c29df72993e2ccbc272972ff9bb16839e6f50b11c1dbe; did=51b36243-a21e-4ee9-8ca2-56037eb23587; sid=d1210c62-d9de-4ee4-8734-7673df07af27",
		BODY_BEGIN,
			"{"client_id":"e586fabad2bfc03bf416f6a5419837a4","redirect_uri":"https://demo.l7r-test.nikecloud.com.cn/","scope":"openid nike.digital profile email phone flow","code_challenge":"{codeChallenger}","code_challenge_method":"S256","state":"{state}","flow":"LOGIN"}",
		BODY_END
	);
//TokenCheckV1
	ns_end_transaction("TokenCheckV1", NS_AUTO_STATUS);
	//TokenGenV1
    ns_start_transaction("TokenGenV1");
	ns_web_url ("token",
		"URL=https://accounts-test.nike.com.cn/token/v1",
		"METHOD=POST",
		"HEADER=sec-ch-ua:\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\"",
		"HEADER=sec-ch-ua-mobile:?0",
		"HEADER=Content-Type:application/x-www-form-urlencoded",
		"HEADER=Origin:https://demo.l7r-test.nikecloud.com.cn",
		"HEADER=Sec-Fetch-Site:cross-site",
		"HEADER=Sec-Fetch-Mode:cors",
		"HEADER=Sec-Fetch-Dest:empty",
		"HEADER=Accept-Language:en-US,en;q=0.9",
		BODY_BEGIN,
			"client_id=e586fabad2bfc03bf416f6a5419837a4&code={code}&redirect_uri=https%3A%2F%2Fdemo.l7r-test.nikecloud.com.cn%2F&code_verifier={codeVerifier}&grant_type=authorization_code",
		BODY_END
	);

	ns_end_transaction("TokenGenV1", NS_AUTO_STATUS);
	//ns_save_data_eval("/home/cavisson/work/access_token/access_token.txt", 0, "{dyn_token_jp}");
		
    // Save token in buffer and parameter
	last_token_gen_time = cur_ts;
	ns_chk_strcpy(dyn_token_buf, ns_eval_string("{dyn_token_jp}"), MAX_TOKEN_SIZE);
	ns_save_string(dyn_token_buf, "token");		
	
//#ifdef NS_DEBUG_ON
    fprintf(stdout, "Token(): Token generated and saved in buffer and token parameter. dyn_token_buf = %s, token = %s\n", dyn_token_buf, ns_eval_string("{token}"));
//#endif
  
	ns_page_think_time(1);	
}
