/*-----------------------------------------------------------------------------
    Name: Util
    Generated By: Brajesh Singh
-----------------------------------------------------------------------------*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ns_string.h"
#include <time.h>
#include <signal.h>

static initialize_job_id()
{
	ns_advance_param("dbid1");  
	ns_advance_param("dbid2");
	ns_advance_param("dbid3");
	ns_advance_param("dbid4");
	ns_advance_param("dbid5");  
	 
	
	char Var1[64]="";
	char Var2[64]="";
	char Var3[64]="";
	char Var4[64]="";
	char Var5[64]="";
	char job[512]="";

	snprintf(Var1,64,"%s",ns_eval_string("{dbid1}"));
	snprintf(Var2,64,"%s",ns_eval_string("{dbid2}"));
	snprintf(Var3,64,"%s",ns_eval_string("{dbid3}"));
	snprintf(Var4,64,"%s",ns_eval_string("{dbid4}"));
	snprintf(Var5,64,"%s",ns_eval_string("{dbid5}"));
	snprintf(job,512,"%s-%s-%s-%s-%s",Var1,Var2,Var3,Var4,Var5);
	ns_save_string(job, "job-id");   
    
}


//ETA Logic

int set_think_time_for_cmd_qry(char *tx_name, char *cmd_or_qry, int *loop_count)
{
double cmd_eta_sec;
char cmd_status[64 + 1] = "Not Set";
char cmd_eta_buf[64 + 1];
int param_val_len = 64;    
    

    param_val_len = 64;
    ns_get_param_val("{cmd_status_jp}", cmd_status, &param_val_len);
    
    param_val_len = 64;
    ns_get_param_val("{cmd_eta_jp}", cmd_eta_buf, &param_val_len);
    
    cmd_eta_sec = (double )atoi((const char *)cmd_eta_buf)/1000; 
//printf("Etatimesec %d", cmd_eta_sec);
   

    (*loop_count)++;
    if(*loop_count > 200)
    {
        fprintf(stderr, "Error: For NVM=%d, User=%d, Session=%d, CMD is not completed for transaction %s with cmd_status = %s,  ETA = %0.3f seconds in max total loop_count = %d\n",ns_get_nvmid(),ns_get_userid(),ns_get_sessid(),tx_name, cmd_status, *loop_count);
        return(-2);        
    }
    
    if(!strcmp(cmd_status, "COMPLETED")) // completed
    {
        if(!strcmp(cmd_or_qry, "CMD")) // method is called for CMD
        {
            fprintf(stderr, "Warning: For NVM=%d, User=%d, Session=%d, Status is completed for CMD transaction %s with ETA = %0.3f seconds which should not happen.\n",ns_get_nvmid(),ns_get_userid(),ns_get_sessid(), tx_name, cmd_eta_sec); 
        }
        else
            cmd_eta_sec = 0; // We must set to 0 as think time is included in tx as tx is ended after think time
        
        ns_page_think_time(200);
#ifdef NS_DEBUG_ON
        fprintf(stdout, "For NVM=%d, User=%d, Session=%d,Transaction is COMPLETED for transaction %s. Setting think time to %0.3f sec. loop_count = %d\n",ns_get_nvmid(),ns_get_userid(),ns_get_sessid(),tx_name, cmd_eta_sec, *loop_count); 
#endif   
        return (1); // Command is completed          
    }
    
    if(!strcmp(cmd_status, "PENDING") || !strcmp(cmd_status, "IN_PROGRESS")) // Not completed yet - in progress
    {
        if(cmd_eta_sec == 0)
        {
            fprintf(stderr, "Error:For NVM=%d, User=%d, Session=%d, Transaction %s is not compelte with status = %s but ETA is 0 \n",ns_get_nvmid(),ns_get_userid(),ns_get_sessid(),tx_name, cmd_status, cmd_eta_sec);
            // cmd_eta_sec = 10;        
        }
#ifdef NS_DEBUG_ON
        fprintf(stdout, "For NVM=%d, User=%d, Session=%d status is %s, Setting think time after transaction %s of value %0.3f seconds. loop_count = %d\n",ns_get_nvmid(),ns_get_userid(),ns_get_sessid(),cmd_status, tx_name, cmd_eta_sec, *loop_count); 
#endif   

        ns_start_transaction("Get_Checkout_Previews_V3_QRY_MEMBER_ETA");
       
       // ns_page_think_time(cmd_eta_sec );
        ns_page_think_time(0.2);
      // double LeftEta_Time =200 - cmd_eta_sec;
      // ns_page_think_time(LeftEta_Time);

    // printf("Etatimesec %f", LeftEta_Time);
      

        // ns_page_think_time(0.1);
        
        ns_end_transaction("Get_Checkout_Previews_V3_QRY_MEMBER_ETA", NS_AUTO_STATUS);  
        return(0); // No completed

    }
    
    // Failure status
    // Code should not come here as on failure, session will stop and think method will not be called
    fprintf(stderr, "For NVM=%d, User=%d, Session=%d,Warning: Got failure status %s for transaction %s of ETA %0.3f seconds\n", cmd_status, tx_name, cmd_eta_sec);     
    //ns_page_think_time(cmd_eta_sec ); 
   ns_page_think_time(0.2); 
  //printf( "ETA time %d",cmd_eta_sec );

      

#ifdef NS_DEBUG_ON
        fprintf(stdout, "For NVM=%d, User=%d, Session=%d,Transaction failed for transaction %s ETA is %0.3f sec. loop_count = %d\n",ns_get_nvmid(),ns_get_userid(),ns_get_sessid(),tx_name, cmd_eta_sec, *loop_count); 
#endif          
    return(-1); // Command failed
}




//-----------Loging data in file------------------------


char *nslb_get_cur_date_time_local(char *time_string, int need_to_block_signal)
{     
    long    tloc;
    struct  tm result;
    struct  tm *lt; 
    sigset_t sigset, oldset;
    
    (void)time(&tloc);
  
    //If need_to_block_signal is set then block all signals and unblock once calculated cur time stamp  
    if (need_to_block_signal == 1) { 
      sigemptyset(&sigset);
      sigfillset(&sigset);
      sigprocmask(SIG_BLOCK, &sigset, &oldset);
      lt = localtime_r(&tloc, &result);
      sigprocmask(SIG_UNBLOCK, &sigset, &oldset);
    } else 
        lt = localtime_r(&tloc, &result);
    
    if (lt == (struct tm *)NULL)
      strcpy(time_string, "Error|Error");
    else 
      sprintf(time_string, "%02d/%02d/%02d %02d:%02d:%02d",  lt->tm_mon + 1, lt->tm_mday, (1900 + lt->tm_year)%2000, lt->tm_hour, lt->tm_min, lt->tm_sec);
    return(time_string);
}

void log_txn_time(char *txn_name, char *trace_id) {
  static int txn_time_threshold = 0; // if txn time is more than this then only will be logged.
  static char filename[] = "txn_summary.txt";
  
  
  int txn_time_msec = ns_get_transaction_time(txn_name);
  int txn_status = ns_get_tx_status(txn_name);
//
//#ifdef NS_DEBUG_ON
//  if(1)
//#else
//  if ((txn_status != 0 && txn_status != 2 && txn_status != 3 && txn_status != 4) /*skip 1xx, 2xx, 3xx, Req. Ok.*/
//      || (txn_time_msec >= txn_time_threshold)) 
//#endif
    
  {
    int pg_status = ns_get_page_status();
    int url_status_code = ns_url_get_http_status_code();
    long cur_time_msec;
    nslb_get_cur_timestamp_ms(&cur_time_msec);
    char date_time_buffer[64];
    nslb_get_cur_date_time_local(date_time_buffer, 1);


    char trace_id_buf[24 + 1];
    char server_date[64 + 1];
    char x_swift_savetime[64 + 1];
    char ali_swift_global_time[64 + 1];
    char x_nike_zhenghe_timing_ms[64 + 1];
    int param_val_len = 64;

    // Must copy in a buffer as next get param api update the buffer returned by eval string
    if(trace_id != NULL)
        strncpy(trace_id_buf, trace_id, 24);
    else
        strcpy(trace_id_buf, "-");
    if(trace_id_buf[17 - 1] == '\r')
        trace_id_buf[17 - 1] = '\0';
        
    param_val_len = 64;
    ns_get_param_val("{server_date_sp}", server_date, &param_val_len);
    if(server_date[param_val_len - 1] == '\r')
        server_date[param_val_len - 1] = '\0';
  
    param_val_len = 64;
    ns_get_param_val("{x_swift_savetime_sp}", x_swift_savetime, &param_val_len);
    if(x_swift_savetime[param_val_len - 1] == '\r')
        x_swift_savetime[param_val_len - 1] = '\0';
    
  
    param_val_len = 64;
    ns_get_param_val("{ali_swift_global_savetime_sp}", ali_swift_global_time, &param_val_len);
    if(ali_swift_global_time[param_val_len - 1] == '\r')
        ali_swift_global_time[param_val_len - 1] = '\0';
  
    param_val_len = 64;
    ns_get_param_val("{x_nike_zhenghe_timing_ms_sp}", x_nike_zhenghe_timing_ms, &param_val_len);
    if(x_nike_zhenghe_timing_ms[param_val_len - 1] == '\r')
        x_nike_zhenghe_timing_ms[param_val_len - 1] = '\0';

    ns_save_data_ex(filename, NS_TRUNC_FILE, "%ld|%s|%s|%s|%s|%d|", cur_time_msec, date_time_buffer, trace_id_buf, txn_name, ns_get_status_name(pg_status), url_status_code);
  //  printf("ETA time-------%s"cmd_eta_sec);
  }


}


